CREATE TABLE CLUB (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE PERSONNE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    date_naissance DATE NOT NULL,
    club_id INT,
    FOREIGN KEY (club_id) REFERENCES CLUB(id)
);

INSERT INTO CLUB (name) VALUES ('Default');